### DISCUSSION TITLE
Hardware Configuration and Examples

### DISCUSSION THREAD

**Discussion by emi-probot** [ICube-Robotics/ethercat_driver_ros2#112] [Q&A]
Howdy! 

I am currently making a very simple system that I would like to control with ros2_control. 
I have my system configured to the point where I can see my hardware when I run `ethercat slave`. This is the output of that:

```
0  0:0  PREOP  +  EK1100 EtherCAT-Koppler (2A E-Bus)
1  0:1  PREOP  +  EL2809 16K. Dig. Ausgang 24V, 0.5A
```

I am hooked up to an EK1100. Connected to the EK1100 is an EL2809. I keep running into an issue with how my configuration file is set up for the EL2809. I tried to replicate what I found on the [Generic EtherCAT Slave configuration page](https://icube-robotics.github.io/ethercat_driver_ros2/user_guide/config_generic_slave.html) but I was not successful. 

This is the output I get when I try to launch my gpio_controller:

```
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ros2_control_node-1]: process started with pid [41943]
[INFO] [robot_state_publisher-2]: process started with pid [41945]
[INFO] [spawner-3]: process started with pid [41947]
[INFO] [spawner-4]: process started with pid [41949]
[robot_state_publisher-2] [INFO] [1710875922.657909569] [robot_state_publisher]: got segment world
[ros2_control_node-1] [INFO] [1710875922.673751595] [controller_manager]: Subscribing to '~/robot_description' topic for robot description file.
[ros2_control_node-1] [INFO] [1710875922.674848217] [controller_manager]: update rate is 100 Hz
[ros2_control_node-1] [INFO] [1710875922.675022291] [controller_manager]: RT kernel is recommended for better performance
[ros2_control_node-1] [INFO] [1710875922.685267828] [controller_manager]: Received robot description file.
[ros2_control_node-1] [INFO] [1710875922.685363314] [resource_manager]: Loading hardware 'gpio_test' 
[ros2_control_node-1] [INFO] [1710875922.687664890] [resource_manager]: Initialize hardware 'gpio_test' 
[ros2_control_node-1] [INFO] [1710875922.687950850] [EthercatDriver]: gpios
[ros2_control_node-1] GenericEcSlave: failed to load drive configuration: bad file: /home/probot-linux-pc/dev_ws/install/gpio_controller/share/gpio_controller/beckhoff_hardware_config/EL2809.yaml
[ros2_control_node-1] [FATAL] [1710875922.689081280] [EthercatDriver]: Setup of GPIO module 1 FAILED.
[ros2_control_node-1] [INFO] [1710875922.689210299] [resource_manager]: Failed to initialize hardware 'gpio_test'
[ros2_control_node-1] [WARN] [1710875922.689216751] [resource_manager]: System hardware component 'gpio_test' from plugin 'ethercat_driver/EthercatDriver' failed to initialize.
[ros2_control_node-1] [ERROR] [1710875922.689249737] [controller_manager]: The published robot description file (urdf) seems not to be genuine. The following error was caught:Wrong state or command interface configuration.
[ros2_control_node-1] missing state interfaces:
[ros2_control_node-1] ' gpio_0/dig_output.1 '	
[ros2_control_node-1] missing command interfaces:
[ros2_control_node-1] ' gpio_0/dig_output.1 '	
[spawner-4] [INFO] [1710875924.920796923] [spawner_gpio_controller]: Waiting for '/controller_manager' services to be available
[spawner-3] [INFO] [1710875924.929388596] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' services to be available
```
Below is my configuration file for the EL2809. I am not very confident in this file and would love to learn more about how ethercat_driver would like the files to be formatted. 
```
# Configuration file for Beckhoff EL2809
# All data was found in the data sheet for this module
 vendor_id: 0x00000002
 product_id: 0x07fc3052
 rpdo:  # RxPDO
   - index: 0x1a00
     channels:
       - {index: 0x6000, sub_index: 1, type: bool, command_interface: dig_output.1}

   - index: 0x1a01
     channels:
       - {index: 0x6010, sub_index: 1, type: bool}

   - index: 0x1a02
     channels:
       - {index: 0x6020, sub_index: 1, type: bool}

   - index: 0x1a03
     channels:
       - {index: 0x6030, sub_index: 1, type: bool}

   - index: 0x1a04
     channels:
       - {index: 0x6040, sub_index: 1, type: bool}

   - index: 0x1a05
     channels:
       - {index: 0x6050, sub_index: 1, type: bool}

   - index: 0x1a06
     channels:
       - {index: 0x6060, sub_index: 1, type: bool}

   - index: 0x1a07
     channels:
       - {index: 0x6070, sub_index: 1, type: bool}


   - index: 0x1a08
     channels:
       - {index: 0x6080, sub_index: 1, type: bool}

   - index: 0x1a09
     channels:
       - {index: 0x6090, sub_index: 1, type: bool}

   - index: 0x1a0A
     channels:
       - {index: 0x60A0, sub_index: 1, type: bool}

   - index: 0x1a0B
     channels:
       - {index: 0x60B0, sub_index: 1, type: bool}

   - index: 0x1a0C
     channels:
       - {index: 0x60C0, sub_index: 1, type: bool}

   - index: 0x1a0D
     channels:
       - {index: 0x60D0, sub_index: 1, type: bool}

   - index: 0x1a0E
     channels:
       - {index: 0x60E0, sub_index: 1, type: bool}

   - index: 0x1a0F
     channels:
       - {index: 0x60F0, sub_index: 1, type: bool}

 sm:  # Sync Manager
   - {index: 0, type: output, pdo: rpdo, watchdog: enable}
```
Below is my XACRO file for the description. I don't have a robot with any joints (for now) so I just made a link to get the controller_manger happy (it seems it is not happy still).
```
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="gpio">


    <link name = "world">
        <origin xyz="0 0 0" rpy="0 0 0" />
    </link>


    <ros2_control name="gpio_test" type="system">
       <hardware>
            <plugin>ethercat_driver/EthercatDriver</plugin>
            <param name="master_id">0</param>
            <param name="control_frequency">100</param>
        </hardware>

    <gpio name="gpio_0">
        <command_interface name="dig_output.1"/>
        <state_interface name="dig_output.1"/>

        <ec_module name="EL2809">
            <plugin>ethercat_generic_plugins/GenericEcSlave</plugin>
            <param name="alias">0</param>
            <param name="position">1</param>
            <param name="slave_config">$(find gpio_controller)/beckhoff_hardware_config/EL2809.yaml</param>
        </ec_module>
    </gpio>
    </ros2_control>


</robot>
```
And here is my controller configuration file too:

```
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gpio_controller:
      type: gpio_controller/GPIOController


gpio_controller:
  ros__parameters:

    gpios:
      - gpio_0

    state_interfaces:
      gpio_0:
      - dig_output.1

    command_interfaces:
      gpio_0:
      - dig_output.1
```

I apologize if this is not the right place to post this. Please direct me to the right place if possible. 

Thank you in advance to anyone who can help!

Best, 
Emi

**Comment by yguel** [comment]
Hi Emi,
First of all the problem come from the yaml file as stated by the error line:
"GenericEcSlave: failed to load drive configuration: bad file: /home/probot-linux-pc/dev_ws/install/gpio_controller/share/gpio_controller/beckhoff_hardware_config/EL2809.yaml"

You can have a look at the 4-channel digital output configuration file in the library: https://github.com/ICube-Robotics/ethercat_driver_ros2_examples/blob/main/ethercat_slave_description/config/beckhoff/beckhoff_el2124.yaml

Tip: an other document is very useful apart from the datasheet is the ESI (EtherCAT Slave Information file). It provides hardware information in a condensed format (link here https://www.beckhoff.com/en-en/products/i-o/ethercat-terminals/el2xxx-digital-output/el2809.html? a zip containing all the ESI files, the one I looked was Beckhoff EL2xxx.xml).
To have more information you can have a look to it, it should provides details close to the yaml file and matching the datasheet. 

As I understand it, those modules are digital output, so usually one commands them to output some data using their rpdo.
It looks to me from the ESI file (Beckhoff EL2xxx.xml) that the index you use are tpdo so either you should change rpdo by tpdo in your yaml file or you are not using the correct registers.
Furthermore if you are providing output with boolean value, I think masks are missing since for boolean types only one bit is used.
An other point is that your product_id is 0x07fc3052 which corresponds (again using the ESI file) to an EL2044.
For EL2809 the product_id (or product code) are:
0x0AF93052
So I would propose a file more like below
```yaml
# Configuration file for Beckhoff EL2809
# All data was found in the ESI file for this module
vendor_id: 0x00000002
product_id: 0x0af93052
rpdo1: # RxPDO
  - index: 0x1600
    channels:
      - {
          index: 0x7000,
          sub_index: 0x01,
          type: bool,
          mask: 1,
          command_interface: dig_output.1,
        }
  - index: 0x1601
    channels:
      - {
          index: 0x7010,
          sub_index: 0x01,
          type: bool,
          mask: 2,
          command_interface: dig_output.2,
        }
  - index: 0x1602
    channels:
      - {
          index: 0x7020,
          sub_index: 0x01,
          type: bool,
          mask: 4,
          command_interface: d_output.3,
        }
  - index: 0x1603
    channels:
      - {
          index: 0x7030,
          sub_index: 0x01,
          type: bool,
          mask: 8,
          command_interface: d_output.4,
        }
  - index: 0x1604
    channels:
      - {
          index: 0x7040,
          sub_index: 0x01,
          type: bool,
          mask: 16,
          command_interface: d_output.5,
        }
  - index: 0x1605
    channels:
      - {
          index: 0x7050,
          sub_index: 0x01,
          type: bool,
          mask: 32,
          command_interface: d_output.6,
        }
  - index: 0x1606
    channels:
      - {
          index: 0x7060,
          sub_index: 0x01,
          type: bool,
          mask: 64,
          command_interface: d_output.7,
        }
  - index: 0x1607
    channels:
      - {
          index: 0x7070,
          sub_index: 0x01,
          type: bool,
          mask: 128,
          command_interface: d_output.8,
        }
rpdo2:
  - index: 0x1608
    channels:
      - {
          index: 0x7080,
          sub_index: 0x01,
          type: bool,
          mask: 1,
          command_interface: d_output.9,
        }
  - index: 0x1609
    channels:
      - {
          index: 0x7090,
          sub_index: 0x01,
          type: bool,
          mask: 2,
          command_interface: d_output.10,
        }
  - index: 0x160a
    channels:
      - {
          index: 0x70a0,
          sub_index: 0x01,
          type: bool,
          mask: 4,
          command_interface: d_output.11,
        }
  - index: 0x160b
    channels:
      - {
          index: 0x70b0,
          sub_index: 0x01,
          type: bool,
          mask: 8,
          command_interface: d_output.12,
        }
  - index: 0x160c
    channels:
      - {
          index: 0x70c0,
          sub_index: 0x01,
          type: bool,
          mask: 16,
          command_interface: d_output.13,
        }
  - index: 0x160d
    channels:
      - {
          index: 0x70d0,
          sub_index: 0x01,
          type: bool,
          mask: 32,
          command_interface: d_output.14,
        }
  - index: 0x160e
    channels:
      - {
          index: 0x70e0,
          sub_index: 0x01,
          type: bool,
          mask: 64,
          command_interface: d_output.15,
        }
  - index: 0x160f
    channels:
      - {
          index: 0x70f0,
          sub_index: 0x01,
          type: bool,
          mask: 128,
          command_interface: d_output.16,
        }
sm: # Sync Manager
  - { index: 0, type: output, pdo: rpdo1, watchdog: enable }
  - { index: 1, type: output, pdo: rpdo2, watchdog: enable }
```
I cannot test it (since we do not have this slave), but if you got a working file, we would be happy to have the feedback to add the config file to the library.

- all the best,

**Comment by yguel** [comment]
Just a simple other idea, have you verified that your config file is well installed: 
Can you access the file ?
``` bash
ls  /home/probot-linux-pc/dev_ws/install/gpio_controller/share/gpio_controller/beckhoff_hardware_config/EL2809.yaml
```

**Reply by emi-probot** [reply]
Thank you so much for your above reply and this inquiry. It appears I cannot access the file. What could be causing this?

**Reply by emi-probot** [reply]
I ended up just copying `beckhoff_hardware_config/EL2809.yaml ` to the `/home/probot-linux-pc/dev_ws/install/gpio_controller/share/gpio_controller` directory and it is now loaded. My control refuses to spawn now but I think that is a separate issue. Once I have this resolved and running properly I will do the same with my EL1809 module in case you would want to add to the config file .

**Reply by yguel** [reply]
I just updated the file I provided to you (in my first answer) noticing that the EL2809 uses a weird configuration with 2 sync managers each for a set of 8 channels.
Now you should be able to use all the 16 channels.
In the xacro file, we use statements like that:
```xml
<param name="slave_config">$(find myproject_description)/config/beckhoff_el5101.yaml</param>
```
then the files are automatically found, otherwise you must specify in your CMakeLists.txt that the files should be installed in the repository they are looked for.

**Reply by yguel** [reply]
Correction to my last message. In fact the case with 2 sync manager for rpdo was not covered.
So the only way to make it work with the actual generic slave is to only use the first 8 channels  like in the following configuration file:
```yaml
# Configuration file for Beckhoff EL2809
# All data was found in the ESI file for this module
vendor_id: 0x00000002
product_id: 0x0af93052
rpdo: # RxPDO
  - index: 0x1600
    channels:
      - {
          index: 0x7000,
          sub_index: 0x01,
          type: bool,
          mask: 1,
          command_interface: dig_output.1,
        }
  - index: 0x1601
    channels:
      - {
          index: 0x7010,
          sub_index: 0x01,
          type: bool,
          mask: 2,
          command_interface: dig_output.2,
        }
  - index: 0x1602
    channels:
      - {
          index: 0x7020,
          sub_index: 0x01,
          type: bool,
          mask: 4,
          command_interface: d_output.3,
        }
  - index: 0x1603
    channels:
      - {
          index: 0x7030,
          sub_index: 0x01,
          type: bool,
          mask: 8,
          command_interface: d_output.4,
        }
  - index: 0x1604
    channels:
      - {
          index: 0x7040,
          sub_index: 0x01,
          type: bool,
          mask: 16,
          command_interface: d_output.5,
        }
  - index: 0x1605
    channels:
      - {
          index: 0x7050,
          sub_index: 0x01,
          type: bool,
          mask: 32,
          command_interface: d_output.6,
        }
  - index: 0x1606
    channels:
      - {
          index: 0x7060,
          sub_index: 0x01,
          type: bool,
          mask: 64,
          command_interface: d_output.7,
        }
  - index: 0x1607
    channels:
      - {
          index: 0x7070,
          sub_index: 0x01,
          type: bool,
          mask: 128,
          command_interface: d_output.8,
        }
sm: # Sync Manager
  - { index: 0, type: output, pdo: rpdo, watchdog: enable }
```
It is always possible to write a custom slave implementation.
However I think that it will not be too complex to upgrade the generic slave configuration to take into account the case with multiple synchronization managers with multiple rpdos and tpdos.
I will find a way to update the generic slave implementation to accept multiple rpdo and tpdo like in the first message which looks like a good generic way to configure it.

I have just a thing to figure out, how to specify the tags for rpdos and tpdos.
