### ISSUE TITLE
invalid tag ec_module

### ISSUE THREAD

**Issue by enriLoniterp** [ICube-Robotics/ethercat_driver_ros2#10]
hi @mcbed,
im trying your integration in my example code.
I've tried to follow your guide in READ.ME but i haven't the expected results.

1. I add `ethercat_driver_ros2` in my worskspace with my other packages to run my RViz simulation with my ethercat driver
2. Everything compiled, even if put another digital output, it is an `Beckhoff el2809` and i made its plugin following the others examples you previously add
3. i have installed master Igh and it is all ok with it (personally tested)
4. i had in my ros2_control file the the ethercat-driver as you explained
5. added EcModule in ros2_control description file
6. For interfacing controllers with EtherCAT Slave Modules i tried your example with an EtherCAT IO modules 
  <gpio bane="MYGPIO"> etc. etc

in 4. it gives me this error ros2_control
```
[ros2_control_node-5] terminate called after throwing an instance of 'std::runtime_error'
[ros2_control_node-5]   what():  invalid tag name ec_module
```
it seems it doesn't understand that it is Hardware resource

and when i don't delete 6. it literally don't start and stop with error on launch.

What is should modify?

**Comment by enriLoniterp** [comment]
Thank you very much for your fast reply.

Consider i'm using MoveIt tutorials packages and i'm using a panda robot.
My final target is to turn on a  led on my BeckHoff EL2809 16-digital outputs through ROS 2.

To answer your question.
- Which branch are you using and which version of ROS2 ? main branch and i'm using ROS 2 Humble
- ```
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="panda_ros2_control" params="name initial_positions_file">
        <xacro:property name="initial_positions" value="${load_yaml(initial_positions_file)['initial_positions']}"/>

        <ros2_control name="${name}" type="system">
            <hardware>
                <plugin>mock_components/GenericSystem</plugin>
            </hardware>

            <hardware>
                <plugin>ethercat_driver/Ethercatdriver</plugin>
                <param name="master_id">0</param>
                <param name="control_frequency">100</param>
            </hardware>



            <ec_module name="ECModule">
                <plugin>etherca_plugins/ECModule</plugin>
                <param name="alias">0</param>
                <param name="position">1</param>
           </ec_module>

            <gpio name="myGPIO">
            <command_interface name="dig_output.1"/></gpio>
            <ec_module name="EL2809">
                <plugin>etherca_plugins/Beckhoff_EL2809</plugin>
                <param name="alias">0</param>
                <param name="position">1</param>
                <param name="do.1">dig_output.2</param>
            </ec_module>
            </gpio> 


            <joint name="panda_joint1">
                <command_interface name="position"/>
                <state_interface name="position">
                  <param name="initial_value">${initial_positions['panda_joint1']}</param>
                </state_interface>
                <state_interface name="velocity"/>
            </joint>
            <joint name="panda_joint2">
                <command_interface name="position"/>
                <state_interface name="position">
                  <param name="initial_value">${initial_positions['panda_joint2']}</param>
                </state_interface>
                <state_interface name="velocity"/>
            </joint>
            <joint name="panda_joint3">
                <command_interface name="position"/>
                <state_interface name="position">
                  <param name="initial_value">${initial_positions['panda_joint3']}</param>
                </state_interface>
                <state_interface name="velocity"/>
            </joint>
            <joint name="panda_joint4">
                <command_interface name="position"/>
                <state_interface name="position">
                  <param name="initial_value">${initial_positions['panda_joint4']}</param>
                </state_interface>
                <state_interface name="velocity"/>
            </joint>
            <joint name="panda_joint5">
                <command_interface name="position"/>
                <state_interface name="position">
                  <param name="initial_value">${initial_positions['panda_joint5']}</param>
                </state_interface>
                <state_interface name="velocity"/>
            </joint>
            <joint name="panda_joint6">
                <command_interface name="position"/>
                <state_interface name="position">
                  <param name="initial_value">${initial_positions['panda_joint6']}</param>
                </state_interface>
                <state_interface name="velocity"/>
            </joint>
            <joint name="panda_joint7">
                <command_interface name="position"/>
                <state_interface name="position">
                  <param name="initial_value">${initial_positions['panda_joint7']}</param>
                </state_interface>
                <state_interface name="velocity"/>
            </joint>
        </ros2_control>
    </xacro:macro>
</robot>
```

**Comment by mcbed** [comment]
I don't know if this is the issue but 2 things:
1. I'm not sure this can work in ros2_control as you have here 2 plugins for the same system which I think will fail.
```xml
<hardware>
    <plugin>mock_components/GenericSystem</plugin>
</hardware>

<hardware>
    <plugin>ethercat_driver/Ethercatdriver</plugin>
    <param name="master_id">0</param>
    <param name="control_frequency">100</param>
</hardware>
```
2. Each ec_module is designed to be a child of a joint, gpio, or sensor
```xml
       <ec_module name="ECModule">
            <plugin>etherca_plugins/ECModule</plugin>
            <param name="alias">0</param>
            <param name="position">1</param>
       </ec_module>

```

**Comment by mcbed** [comment]
Putting the 2 plugins inside a single ros2_control system should not work as it is against the logic of the framework. A ros2_control system is intended to represent a single communication channel. So here you have 2 of them: one for the panda and another for ethercat. You should then have 2 ros2_control systems in your description. 

In 2. you still have the closing `gpio` tag that exludes your ec_module from the component. 

For the last, in the `gpios` parameter you should specify the names of the gpios you want to control. In your case its `myGPIO`. 
Then, you specify the interface per listed gpio: 
```yaml
command_interfaces:
    myGPIO:
        - dig.output.1
```

**Comment by enriLoniterp** [comment]
Hi @mcbed,
sorry for this question, i'm still learning `ros2_control`.

Thank you for the first suggestion, i should delete mock component and only test with `ethercat_drivers`, but i still don't know how to make a simple write with etherCAT master with your `ethercat_drivers`.

For example, i've created a simple application including `ros2_control` and your etherCAT drivers and i want to actually turn on a led on `Beckhoff EL2809`, in my experience it's just writing with **EC_WRITE8** from my `IgH master` or other simple macro or functions and the led will turn on. I want to do the same but included in a ROS2 application with your drivers. I've seen you published a simple `gpio controller` and i'm interested to make it part of my initial simple application. But what are the moves should i do? I think:

1. add my gpio 16 digital ouput beckhoff on plugin list? Done
2. add succesfully the `ethercat_drivers` to my project ros2? Done
3. write a node in which i instantiate your `gpiocontroller `and make a write to my `Beckhoff el2809`? from now i'm still a bit confused..
4. ..
5. ..

Hope you can help,
but thanks you a lot anyway!

Enrico

**Comment by mcbed** [comment]
Did you write the plugin driver for your module inheriting from the `ethercat_interface::EcSlave` base class ?

In general you should:
1. write the plugin for your module if not already available in the [list](https://github.com/ICube-Robotics/ethercat_driver_ros2/blob/main/ethercat_plugins/available_plugins.md). Example for Beckhoff  20xx modules [here](https://github.com/ICube-Robotics/ethercat_driver_ros2/blob/main/ethercat_plugins/src/beckhoff_plugins/beckhoff_el20xx.cpp)
2. set up the description of your ec modules in your hardware components with `ec_module` tags and map the interfaces of ros2_control to the module channels. Also some modules reuire additional parameters that can be set in the description. This depends on how the plugin is written.
3. run the `gpio_command_controller` to interact with the interfaces that are mapped to your module channels. You done need a specific node, you can just run it from command prompt with `$ ros2 topic pub ... `

**Comment by enriLoniterp** [comment]
1. i went on `ethercat_driver_ros2/ethercat_plugins/src/beckhoff_plugins` and i added` beckhoff_el2809.cpp` which is my 16 digital output gpio. (i also have on ek1100 you already prepared)
2.  i put in <ros2_control> my ec_module mapped correctly, not added any additional parameters for now, maybe i will. You can find the ros2_control sample if you did moveit2 tutorials on panda robot
3. i don't understand this point, i run gpio_command_controller using one `ros2 control `command or it is a node itself which i can run from bash?  by the way i'd rather prefer writing my node because this ethercat write should represent command sent to my beckhoff element which should move my robot theoretically!

**Comment by mcbed** [comment]
Second, in your controller cofiguration you are missing the gpios see [doc](https://github.com/mcbed/ros2_controllers/blob/gpio_controllers/gpio_controllers/doc/userdoc.rst) : 
```yaml
gpio_command_controller:
  ros_parameters:
    gpios:
        - myGPIO
    command_interfaces:
        myGPIO:
            - dig_output.1
```

**Comment by enriLoniterp** [comment]
Should work this  #way?
```
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    scara_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scara_position_controller:
      type: position_controllers/JointGroupPositionController

    scara_joint_velocity_controller:
      type: scara_joint_velocity_controller/ScaraJointVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gpio_command_controller:
      type: gpio_controllers/GpioCommandController
  

scara_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - joint1
      - joint2
      - joint3

  scara_position_controller:
    ros__parameters:
      joints:
        - joint1
        - joint2
        - joint3

  scara_joint_velocity_controller:
    ros__parameters:
      joints:
        - joint1
        - joint2
        - joint3

  gpio_command_controller:
    ros__parameters:
        gpios:
          - myGPIO
        command_interfaces:
          myGPIO:
            - dig_output.1
        state_interfaces:
            myGPIO:
            - dig_output.1

```

> Second, in your controller cofiguration you are missing the gpios see [doc](https://github.com/mcbed/ros2_controllers/blob/gpio_controllers/gpio_controllers/doc/userdoc.rst) :
> 
> ```yaml
> gpio_command_controller:
>   ros_parameters:
>     gpios:
>         - myGPIO
>     command_interfaces:
>         myGPIO:
>             - dig_output.1
> ```
